import Header from '@/components/header';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-normal p-4 xl:p-24 overflow-x-hidden lg:overflow-x-auto">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
